---
# Source: langfuse/templates/postgresql/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: langfuse
---
# Source: langfuse/templates/postgresql/pvc-postgres.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# Source: langfuse/templates/postgresql/service-postgres.yaml
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgresql
---
# Source: langfuse/templates/postgresql/deployment-postgres.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: langfuse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: langfuse
            - name: POSTGRES_PASSWORD
              value: changeme
            - name: POSTGRES_DB
              value: langfuse
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 5
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
                cpu: 100m
                memory: 256Mi
            limits:
                cpu: "500m"
                memory: 512Mi
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-storage
