namespace:
  create: true
  name: langfuse


postgresql:
  enabled: true
  applicationName: postgresql
  image: postgres:17
  containerName: postgres
  username: langfuse
  password: changeme
  database: langfuse
  volumeName: postgres-storage
  claimName: postgres-storage
  mountPath: /var/lib/postgresql/data
  storageClassName: nfs-prod
  typeService: ClusterIP
  # namespace: langfuse
  replicas: 1
  port: 5432
  storage:
    size: 3Gi
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

redis:
  enabled: true
  applicationName: redis
  image: redis:7
  containerName: redis
  port: 6379
  password: MyRedisPassword
  # namespace: langfuse
  replicas: 1
  typeService: ClusterIP
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

minio:
  enabled: true
  applicationName: minio
  image: minio/minio
  containerName: minio
  port_1: 9000
  port_2: 9001
  minioRootUser: minio
  minioRootPassword: minioPassword
  bucketName: langfuse
  mountPath: /data
  volumeName: minio-storage
  claimName: minio-storage
  storageClassName: nfs-prod
  storage:
    size: 3Gi
  # namespace: langfuse
  replicas: 1
  typeService: NodePort
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

clickhouse:
  enabled: true
  applicationName: clickhouse
  # namespace: langfuse
  image: clickhouse/clickhouse-server
  containerName: clickhouse
  port_1: 8123
  port_2: 9000
  clickhouseDB: clickhouse
  clickhouseUser: clickhouse
  clickhousePassword: clickhouse
  mountPath_data: /var/lib/clickhouse
  volumeName_data: clickhouse-data
  mountPath_logs: /var/log/clickhouse-server
  volumeName_logs: clickhouse-logs
  claimName_data: clickhouse-storage-data
  claimName_logs: clickhouse-storage-logs
  storageClassName: nfs-prod
  storage:
    size_data: 3Gi
    size_logs: 2Gi
  replicas: 1
  typeService: ClusterIP
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

langfuse_worker:
  enabled: true
  applicationName: langfuse-worker
  # namespace: langfuse
  image: langfuse/langfuse-worker:3
  containerName: langfuse-worker
  replicas: 1
  port: 3030
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "2048Mi"

langfuse_web:
  enabled: true
  applicationName: langfuse-web
  # namespace: langfuse
  image: langfuse/langfuse:3
  containerName: langfuse-web
  replicas: 1
  port: 3000
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "2048Mi"
  typeService: NodePort

secret:
  clickhouse:
    CLICKHOUSE_USER: clickhouse
    CLICKHOUSE_PASSWORD: clickhouse
    CLICKHOUSE_DB: langfuse
  minio:
    MINIO_ROOT_USER: minio
    MINIO_ROOT_PASSWORD: miniosecret
  postgresql:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: langfuse
  redis:
    REDIS_PASSWORD: myredissecret
  langfuse: 
    LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY: "miniosecret"
    LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID: "minio"
    LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID: "minio"
    CLICKHOUSE_USER: "clickhouse"
    SALT: "mysalt"
    CLICKHOUSE_PASSWORD: "clickhouse"
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/langfuse"
    LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: "miniosecret"
    REDIS_AUTH: "myredissecret"
    ENCRYPTION_KEY: "0000000000000000000000000000000000000000000000000000000000000000"
    NEXTAUTH_SECRET: "mysecret"
    