# Example values file for Langfuse Helm chart

namespace:
  create: false
  name: langfuse

postgresql:
  enabled: true
  applicationName: langfuse-postgresql
  image: postgres:17
  containerName: postgres
  volumeName: postgres-storage
  claimName: postgres-storage
  mountPath: /var/lib/postgresql/data
  storageClassName: nfs-prod
  typeService: ClusterIP
  replicas: 1
  port: 5432
  storage:
    size: 3Gi
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

redis:
  enabled: true
  applicationName: langfuse-redis
  image: redis:7
  containerName: redis
  port: 6379
  replicas: 1
  typeService: ClusterIP
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

minio:
  enabled: true
  applicationName: langfuse-minio
  image: minio/minio
  containerName: minio
  port_1: 9000
  port_2: 9001
  bucketName: example-bucket
  mountPath: /data
  volumeName: minio-storage
  claimName: minio-storage
  storageClassName: nfs-prod
  storage:
    size: 3Gi
  replicas: 1
  typeService: NodePort
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

clickhouse:
  enabled: true
  applicationName: langfuse-clickhouse
  image: clickhouse/clickhouse-server
  containerName: clickhouse
  port_1: 8123
  port_2: 9000
  mountPath_data: /var/lib/clickhouse
  volumeName_data: clickhouse-data
  mountPath_logs: /var/log/clickhouse-server
  volumeName_logs: clickhouse-logs
  claimName_data: clickhouse-storage-data
  claimName_logs: clickhouse-storage-logs
  storageClassName: nfs-prod
  storage:
    size_data: 3Gi
    size_logs: 2Gi
  replicas: 1
  typeService: ClusterIP
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

langfuse_worker:
  enabled: true
  applicationName: langfuse-worker
  image: langfuse/langfuse-worker:3
  containerName: langfuse-worker
  nameConfigmap: langfuse-configmap
  replicas: 1
  port: 3030
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "2048Mi"

langfuse_web:
  enabled: true
  applicationName: langfuse-web
  image: langfuse/langfuse:3
  containerName: langfuse-web
  replicas: 1
  port: 3000
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "2048Mi"
  typeService: NodePort

secret:
  clickhouse:
    name: clickhouse-secret
    CLICKHOUSE_USER: clickhouse
    CLICKHOUSE_PASSWORD: changeme
    CLICKHOUSE_DB: langfuse
  minio:
    name: minio-secret
    MINIO_ROOT_USER: minio
    MINIO_ROOT_PASSWORD: changeme
  postgresql:
    name: postgres-secret
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: changeme
    POSTGRES_DB: langfuse
  redis:
    name: redis-secret
    REDIS_PASSWORD: changeme
  langfuse:
    name: langfuse-secret
    LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY: "changeme"
    LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID: "minio"
    LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID: "minio"
    SALT: "changeme"
    DATABASE_URL: "postgresql://postgres:changeme@postgres:5432/langfuse"
    LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: "changeme"
    REDIS_AUTH: "changeme"
    ENCRYPTION_KEY: "your-256-bit-hex-key"
    NEXTAUTH_SECRET: "changeme"
