apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.applicationName }}
  # namespace: {{ .Values.redis.namespace }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.redis.applicationName }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.applicationName }}
    spec:
      containers:
        - name: {{ .Values.redis.containerName }}
          image: {{ .Values.redis.image }}
          args:
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
          env:
            - name: REDIS_PASSWORD
              value: {{ .Values.redis.password }}
          ports:
            - containerPort: {{ .Values.redis.port }}
          livenessProbe:
            exec:
              command:
                - redis-cli
                - -a
                - "$(REDIS_PASSWORD)"
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - redis-cli
                - -a
                - "$(REDIS_PASSWORD)"
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
                cpu: {{ .Values.redis.resources.requests.cpu }}
                memory: {{ .Values.redis.resources.requests.memory }}
            limits:
                cpu: {{ .Values.redis.resources.limits.cpu | quote }}
                memory: {{ .Values.redis.resources.limits.memory }}