apiVersion: v1
kind: Service
metadata:
  name: langfuse-{{ .Values.redis.applicationName }}
spec:
  selector:
    app: {{ .Values.redis.applicationName }}
  ports:
    - protocol: TCP
      port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
  type: {{ .Values.redis.typeService }}