apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgresql.claimName }}
  # namespace: {{ .Values.postgresql.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storage.size }}
  storageClassName: {{ .Values.postgresql.storageClassName }}
