apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.postgresql.name }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secret.postgresql.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresql.POSTGRES_PASSWORD }}
  POSTGRES_DB: {{ .Values.secret.postgresql.POSTGRES_DB }}