apiVersion: v1
kind: Service
metadata:
  name: langfuse-{{ .Values.postgresql.applicationName }}
  namespace: {{ .Values.postgresql.namespace }}
spec:
  type: {{ .Values.postgresql.typeService }}
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}
  selector:
    app: {{ .Values.postgresql.applicationName }}
