apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.minio.name }}
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.secret.minio.MINIO_ROOT_USER }}
  MINIO_ROOT_PASSWORD: {{ .Values.secret.minio.MINIO_ROOT_PASSWORD }}