apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.minio.applicationName }}
spec:
  selector:
    app: {{ .Values.minio.applicationName }}
  ports:
    - name: api
      port: {{ .Values.minio.port_1 }}
      targetPort: {{ .Values.minio.port_1 }}
    - name: console
      port: {{ .Values.minio.port_2 }}
      targetPort: {{ .Values.minio.port_2 }}
  type: {{ .Values.minio.typeService }}