apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.clickhouse.claimName_data }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.clickhouse.storage.size_data }}
  storageClassName: {{ .Values.clickhouse.storageClassName }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.clickhouse.claimName_logs }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.clickhouse.storage.size_logs }}
  storageClassName: {{ .Values.clickhouse.storageClassName }}