apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.clickhouse.name }}
type: Opaque
stringData:
  CLICKHOUSE_USER: {{ .Values.secret.clickhouse.CLICKHOUSE_USER }}
  CLICKHOUSE_PASSWORD: {{ .Values.secret.clickhouse.CLICKHOUSE_PASSWORD }}
  CLICKHOUSE_DB: {{ .Values.secret.clickhouse.CLICKHOUSE_DB }}