apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.langfuse_worker.applicationName }}
  # namespace: {{ .Values.langfuse_worker.namespace }}
spec:
  replicas: {{ .Values.langfuse_worker.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.langfuse_worker.applicationName }}
  template:
    metadata:
      annotations:
        configmap.langfuse.hash: "74f6d36a978c1bff234dd0252c80f8895f48f71d356eaca25edfd1673df6423d"
      labels:
        app: {{ .Values.langfuse_worker.applicationName }}
    spec:
      containers:
        - name: {{ .Values.langfuse_worker.containerName }}
          image: {{ .Values.langfuse_worker.image }}
          ports:
            - containerPort: {{ .Values.langfuse_worker.port }}
          resources:
            requests:
                cpu: {{ .Values.langfuse_worker.resources.requests.cpu }}
                memory: {{ .Values.langfuse_worker.resources.requests.memory }}
            limits:
                cpu: {{ .Values.langfuse_worker.resources.limits.cpu | quote }}
                memory: {{ .Values.langfuse_worker.resources.limits.memory }}
          envFrom:
            - configMapRef:
                name: {{ .Values.langfuse_worker.namespace }}-configmap

          env:
            - name: LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: langfuse-secret
                  key: LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY

            - name: LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: langfuse-secret
                  key: LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID

            - name: LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: langfuse-secret
                  key: LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID

            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: langfuse-secret
                  key: CLICKHOUSE_USER

            - name: SALT
              valueFrom:
                secretKeyRef:
                  name: langfuse-secret
                  key: SALT

            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: langfuse-secret
                  key: CLICKHOUSE_PASSWORD

            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: langfuse-secret
                  key: DATABASE_URL

            - name: LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: langfuse-secret
                  key: LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY

            - name: REDIS_AUTH
              valueFrom:
                secretKeyRef:
                  name: langfuse-secret
                  key: REDIS_AUTH

            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: langfuse-secret
                  key: ENCRYPTION_KEY

            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: langfuse-secret
                  key: NEXTAUTH_SECRET