apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.langfuse.name }}
type: Opaque
stringData:
  LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY: "{{ .Values.secret.langfuse.LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY }}"
  LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID: "{{ .Values.secret.minio.MINIO_ROOT_USER }}"
  LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID: "{{ .Values.secret.minio.MINIO_ROOT_USER }}"
  CLICKHOUSE_USER: "{{ .Values.secret.clickhouse.CLICKHOUSE_USER }}"
  SALT: "{{ .Values.secret.langfuse.SALT }}"
  CLICKHOUSE_PASSWORD: "{{ .Values.secret.clickhouse.CLICKHOUSE_PASSWORD }}"
  DATABASE_URL: "postgresql://{{ .Values.secret.postgresql.POSTGRES_USER }}:{{ .Values.secret.postgresql.POSTGRES_PASSWORD }}@{{ .Values.postgresql.applicationName }}:{{ .Values.postgresql.port }}/{{ .Values.secret.postgresql.POSTGRES_DB }}"
  LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: "{{ .Values.secret.minio.MINIO_ROOT_PASSWORD }}"
  REDIS_AUTH: "{{ .Values.secret.redis.REDIS_PASSWORD }}"
  ENCRYPTION_KEY: "{{ .Values.secret.langfuse.ENCRYPTION_KEY }}"
  NEXTAUTH_SECRET: "{{ .Values.secret.langfuse.NEXTAUTH_SECRET }}"