apiVersion: v1
kind: Secret
metadata:
  name: langfuse-secret
#   namespace: langfuse
type: Opaque
stringData:
  LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY: "miniosecret"
  LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID: "minio"
  LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID: "minio"
  CLICKHOUSE_USER: "clickhouse"
  SALT: "mysalt"
  CLICKHOUSE_PASSWORD: "clickhouse"
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/langfuse"
  LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: "miniosecret"
  REDIS_AUTH: "myredissecret"
  ENCRYPTION_KEY: "0000000000000000000000000000000000000000000000000000000000000000"
  NEXTAUTH_SECRET: "mysecret"